
name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Build and push Docker image 1
      - name: Build and Push Docker Image 1
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./14/Dockerfile
          push: true
          tags: ghcr.io/zen/nodejspm2:14

      # 4. Build and push Docker image 2
      - name: Build and Push Docker Image 2
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./16/Dockerfile
          push: true
          tags: ghcr.io/zen/nodejspm2:16

      # 5. Build and push Docker image 3
      - name: Build and Push Docker Image 3
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./18/Dockerfile
          push: true
          tags: ghcr.io/zen/nodejspm2:18

      # 6. Build and push Docker image 4
      - name: Build and Push Docker Image 4
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./19/Dockerfile
          push: true
          tags: ghcr.io/zen/nodejspm2:19
